# Generated by Django 3.2.13 on 2022-04-26 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import novel.users.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('avatar', models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('premium', models.BooleanField(blank=True, default=False)),
                ('premium_expire', models.DateTimeField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, default=3, null=True, verbose_name='Votes')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile data',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', novel.users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('book', models.ManyToManyField(blank=True, related_name='librarys', to='books.Book')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Library data',
            },
        ),
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('c_id', models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Progress ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookprogresses', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookprogresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Progress',
                'verbose_name_plural': 'Book Progresses',
            },
        ),
    ]
