# Generated by Django 3.2.13 on 2022-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='category',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('info', 'Info'), ('mtl', 'mtl')], default='normal', max_length=55),
        ),
    ]
