# Generated by Django 3.2.13 on 2022-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_bookchapterreplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='origin',
            field=models.CharField(blank=True, choices=[('webnovel', 'Webnovel'), ('boxnovel', 'Boxnovel'), ('pandanovel', 'Pandanovel'), ('wuxiaworld', 'Wuxia World'), ('lnmtl', 'LNMTL'), ('other', 'Other')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='book',
            name='revisit',
            field=models.CharField(blank=True, choices=[('webnovel', 'Webnovel'), ('boxnovel', 'Boxnovel'), ('pandanovel', 'Pandanovel'), ('wuxiaworld', 'Wuxia World'), ('lnmtl', 'LNMTL'), ('other', 'Other')], default='webnovel', max_length=55),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit',
            field=models.CharField(blank=True, choices=[('webnovel', 'Webnovel'), ('boxnovel', 'Boxnovel'), ('pandanovel', 'Pandanovel'), ('wuxiaworld', 'Wuxia World'), ('lnmtl', 'LNMTL'), ('other', 'Other')], default='webnovel', max_length=55),
        ),
    ]
