# Generated by Django 3.2.13 on 2022-05-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookchapter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='category',
            field=models.CharField(choices=[('normal', 'Normal'), ('info', 'Info'), ('mtl', 'mtl')], default='normal', max_length=55),
        ),
    ]
