# Generated by Django 3.2.13 on 2022-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220426_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='View Count'),
        ),
    ]
